# Generated by Django 5.2.6 on 2025-10-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Price ID'),
        ),
        migrations.AddField(
            model_name='course',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Product ID'),
        ),
    ]
