# Generated by Django 5.2.6 on 2025-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_course_stripe_price_id_course_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена курса'),
        ),
    ]
