# Generated by Django 5.2.6 on 2025-10-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
